[package]
name = "storm"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-map = "2.7.3"
opts = { path = "opts" }

[target.'cfg(windows)'.dependencies]
parking_lot = "0.12.3"
widestring = "1.1.0"
winapi = { version = "0.3.9", features = ["errhandlingapi", "std", "winbase", "winuser"] }

[workspace]
members = [ "opts" ]
